# Generated by Django 3.1.2 on 2020-10-09 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default=None, max_length=128)),
                ('nutrition_grades', models.CharField(default=None, max_length=1)),
                ('stores', models.CharField(default=None, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=128)),
                ('url', models.CharField(default=None, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default=None, max_length=128)),
                ('nutrition_grades', models.CharField(default=None, max_length=1)),
                ('stores', models.CharField(default=None, max_length=128)),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aliment')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.AddField(
            model_name='aliment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
