# Generated by Django 3.1.2 on 2020-10-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201009_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='substitute',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
