# Generated by Django 3.1.2 on 2020-10-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201016_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aliment',
            old_name='image_url',
            new_name='image_front_thumb_url',
        ),
        migrations.RenameField(
            model_name='substitute',
            old_name='image_url',
            new_name='image_front_thumb_url',
        ),
    ]
