# Generated by Django 3.1.2 on 2020-10-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201016_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='product_name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='substitute',
            name='product_name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, unique=True),
        ),
    ]
