# Generated by Django 3.1.2 on 2020-10-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201023_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aliment',
            old_name='image_front_thumb_url',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='substitute',
            old_name='image_front_thumb_url',
            new_name='image_url',
        ),
    ]
