# Generated by Django 3.1.2 on 2020-10-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201024_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitute',
            name='product_name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
